@startuml
package "ToDoListOrganizer" {
  folder "src" {
    file "app.py"
    file "task_manager.py"
    file "user_auth.py"
    file "project_manager.py"
  }
  folder "templates" {
    file "index.html"
    file "login.html"
    file "project_view.html"
  }
  folder "static" {
    folder "css" {
      file "style.css"
    }
    folder "js" {
      file "main.js"
    }
  }
  folder "tests" {
    file "test_task_manager.py"
    file "test_user_auth.py"
    file "test_project_manager.py"
  }
  file "README.md"
}
@enduml
